name: Documentation Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  docs-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/markdown-link-check.json"

      - name: Check Markdown Formatting
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: "*.md"
          config: ".github/markdownlint.yaml"
